apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kaemon-component
  description: Apis used by the Catalog component of the Lighthouse Developer Portal
  tags:
    - javascript
    - node
  links:
    - url: https://github.com/department-of-veterans-affairs/lighthouse-developer-portal/issues
      title: Issues
      icon: help
    - url: https://department-of-veterans-affairs.github.io/lighthouse-developer-portal/
      title: Docs
      icon: dashboard
    - url: https://backstage.io/
      title: Backstage.io
      icon: web
    - url: https://lighthouseva.slack.com/archives/C020ZR4UL8H
      title: lighthouse-bandicoot slack
      icon: group
  kaemon: lovendahl
pokemon: pikachu
spec:
  type: openapi
  owner: lighthouse-bandicoot
  lifecycle: experimental
  system: lighthouse-developer-portal
