apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lighthouse-hub-monorepo-test
  description: Keeps track of all packages and plugins related to the Lighthouse Hub
  title: 'Lighthouse Hub Test'
  tags:
    - monorepo
  links:
    - url: https://github.com/department-of-veterans-affairs/lighthouse-developer-portal
      title: Lighthouse Hub Monorepo
      icon: web
    - url: https://github.com/department-of-veterans-affairs/lighthouse-developer-portal/issues
      title: Issues
      icon: help
    - url: https://lighthouseva.slack.com/archives/C020ZR4UL8H
      title: lighthouse-bandicoot slack
      icon: slack
  annotations:
    github.com/project-slug: department-of-veterans-affairs/lighthouse-developer-portal
    backstage.io/techdocs-ref: url:https://github.com/department-of-veterans-affairs/lighthouse-developer-portal
spec:
  domain: lighthouse
  system: lighthouse-hub
  type: website
  owner: lighthouse-bandicoot
  lifecycle: experimental
