apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    wsdl: http://webservices.daehosting.com/services/isbnservice.wso?WSDL
  name: testing-soap
  title: TESTING SOAP
spec:
  type: soap
  lifecycle: experimental
  owner: lighthouse-bandicoot
  system: lighthouse-internal-developer-hub
  definition:
    $text: http://webservices.daehosting.com/services/isbnservice.wso?WSDL
